spring:
  profiles:
    active: local
  messages:
    basename: messages/messages
  jpa:
    open-in-view: false
server:
  port: 9966
  servlet:
    context-path: /petclinic/
petclinic:
  security:
    enable: false

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    change-log: classpath:liquibase/master.yml
    url: jdbc:postgresql://localhost:5432/petclinic
    user: postgres
    password: petclinic
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/petclinic
    username: postgres
    password: petclinic
    name: petclinic

---
spring:
  config:
    activate:
      on-profile: mock