node {

    stage("Git Clone") {
        git credentialsId: 'GIT_HUB_CREDENTIALS', url: 'https://github.com/ilovecorea/tutorials', branch: 'main'
    }

    stage('Maven Build') {
        sh 'cd ./k8s-jenkins && mvn clean install'
    }

    stage("Docker build") {
        sh 'docker version'
        sh 'cd ./k8s-jenkins && docker build -t hello-springboot .'
        sh 'docker image list'
        sh 'docker tag hello-springboot ilovecorea/hello-springboot:latest'
    }

    stage("Docker Login") {
        withCredentials([string(credentialsId: 'DOCKER_HUB_PASSWORD', variable: 'PASSWORD')]) {
            sh 'docker login -u ilovecorea -p $PASSWORD'
        }
    }

    stage("Push Image to Docker Hub") {
        sh 'docker push ilovecorea/hello-springboot:latest'
    }

    stage("SSH Into k8s Server") {
        def remote = [:]
        remote.name = 'K8S master'
        remote.host = '100.0.0.2'
        remote.user = 'vagrant'
        remote.password = 'vagrant'
        remote.allowAnyHosts = true

        stage('Put k8s-hello-springboot-deployment.yml onto k8smaster') {
            sshPut remote: remote, from: 'k8s-jenkins/k8s-hello-springboot-deployment.yml', into: '.'
        }

        stage('Deploy spring boot') {
          sshCommand remote: remote, command: "kubectl apply -f k8s-hello-springboot-deployment.yml"
        }
    }
}
