NodeCnt = 2

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.define "jenkins" do |jenkins|
      jenkins.vm.box_download_insecure = true
      jenkins.vm.box = "hashicorp/bionic64"
      jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
      jenkins.vm.network "forwarded_port", guest: 8081, host: 8081
      jenkins.vm.network "forwarded_port", guest: 9090, host: 9090
      jenkins.vm.network "private_network", ip: "192.168.56.1"
      jenkins.vm.hostname = "jenkins"
      jenkins.vm.provider "virtualbox" do |v|
        v.name = "jenkins"
        v.memory = 2048
        v.cpus = 2
      end
      jenkins.vm.provision "shell", privileged: true, inline: $install_jenkins
  end

  config.vm.define "k8s-master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "k8s-master"
    master.vm.network "private_network", ip: "192.168.56.30"
    master.vm.provision :shell, privileged: true, inline: $install_common_tools
    master.vm.provision :shell, privileged: true, inline: $provision_master_node
  end

  (1..NodeCnt).each do |i|
    config.vm.define "k8s-node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "k8s-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{i + 30}"
      node.vm.provision :shell, privileged: true, inline: $install_common_tools
    end
  end
end

$install_jenkins = <<-SHELL
echo "##################################################################################"
echo "  설치 준비"
echo "##################################################################################"
whoami
apt update
apt install -y wget

# Hosts 등록
cat << EOF >> /etc/hosts
192.168.56.30 k8s-master
192.168.56.31 k8s-node1
192.168.56.32 k8s-node2
EOF

echo "##################################################################################"
echo "  JAVA 설치"
echo "##################################################################################"
apt install -y openjdk-8-jdk
#wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz
#tar xvf openjdk-17_linux-x64_bin.tar.gz
#mv jdk-17 /opt/

echo "##################################################################################"
echo "  JAVA_HOME /etc/profile 등록"
echo "##################################################################################"
#cat << EOF >> /etc/profile
#export JAVA_HOME=/opt/jdk-17
#export PATH=$PATH:/opt/jdk-17/bin
#EOF

#source /etc/profile
java --version

echo "##################################################################################"
echo "  Docker 설치"
echo "##################################################################################"

apt update
apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
apt update
apt install -y docker-ce

usermod -aG docker jenkins
usermod -aG docker vagrant

systemctl status docker
docker version

# 메이븐 설치
echo "##################################################################################"
echo "  메이븐 설치"
echo "##################################################################################"
wget https://downloads.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz -P /tmp
tar -xzvf /tmp/apache-maven-3.8.2-bin.tar.gz -C /opt
ln -s /opt/apache-maven-3.8.2 /opt/maven

echo "##################################################################################"
echo "  MAVEN_HOME 설정"
echo "##################################################################################"
cat << EOF >> /etc/profile
export M2_HOME=/opt/maven
export PATH=/opt/maven/bin:$PATH
EOF

source /etc/profile
mvn -version

echo "##################################################################################"
echo "  Jenkins 설치"
echo "##################################################################################"
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
apt-get update
apt-get install -y jenkins
sleep 20 && cp /var/lib/jenkins/secrets/initialAdminPassword /vagrant/password.txt

SHELL

$install_common_tools = <<-SHELL

# ssh password 접속 활성화
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config;
systemctl restart sshd.service

# 방화벽 해제
systemctl stop firewalld && systemctl disable firewalld
systemctl stop NetworkManager && systemctl disable NetworkManager

# Swap 비활성화
swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab

# br_netfilter 모듈 로드
cat <<EOF | tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

# Iptables 커널 옵션 활성화
cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

# permissive 모드로 SELinux 설정(효과적으로 비활성화)
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

# 쿠버네티스 YUM Repository 설정
cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Centos Update
yum -y update

# Hosts 등록
cat << EOF >> /etc/hosts
192.168.56.30 k8s-master
192.168.56.31 k8s-node1
192.168.56.32 k8s-node2
EOF

# 도커 설치
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y containerd.io-1.4.9-3.1.el7 docker-ce-3:20.10.8-3.el7.x86_64 docker-ce-cli-1:20.10.8-3.el7.x86_64


mkdir /etc/docker
cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
EOF
mkdir -p /etc/systemd/system/docker.service.d

# 도커 재시작
systemctl daemon-reload
systemctl enable --now docker


# 쿠버네티스 설치
yum install -y kubelet-1.22.0-0.x86_64 kubeadm-1.22.0-0.x86_64 kubectl-1.22.0-0.x86_64 --disableexcludes=kubernetes
systemctl enable --now kubelet

SHELL

$provision_master_node = <<-SHELL

# 쿠버네티스 초기화 명령 실행
kubeadm init --apiserver-advertise-address 192.168.56.30 --pod-network-cidr=20.96.0.0/12
kubeadm token create --print-join-command > ~/join.sh

# 환경변수 설정
mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

# Kubectl 자동완성 기능 설치
yum install bash-completion -y
source <(kubectl completion bash)
echo "source <(kubectl completion bash)" >> ~/.bashrc

# Calico 설치
curl https://docs.projectcalico.org/manifests/calico.yaml -O
kubectl apply -f calico.yaml

# Dashboard 설치
kubectl apply -f https://kubetm.github.io/yamls/k8s-install/dashboard-2.3.0.yaml
nohup kubectl proxy --port=8001 --address=192.168.56.30 --accept-hosts='^*$' >/dev/null 2>&1 &

SHELL