server:
  port: 8080
jwt:
  auth:
    issuer1:
      issuer-uri: http://localhost:9999/auth/realms/site1
      resource-id: app-cli
      principal-attribute: preferred_username
    issuer2:
      issuer-uri: http://localhost:9999/auth/realms/site2
      resource-id: app-cli
      principal-attribute: preferred_username
logging:
  level:
    org.example: DEBUG
    org.springframework.security: DEBUG