spring:
  security:
    oauth2:
      resourceserver:
        site1:
          jwk-set-uri: http://localhost:9999/auth/realms/site1/.well-known/openid-configuration
        site2:
          introspection-uri: http://localhost:9999/auth/realms/site2/protocol/openid-connect/token/introspect
          introspection-client-id: site2-client
          ntrospection-client-secret: xL9guTuyvDCh0dP0VRaCSk9Xrrsej9Md