server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/lemonhc
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: lemonhc-oidc-client
      principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG